In [1]:
import numpy as np

In [2]:
np.array([4,45,5,61])

array([ 4, 45,  5, 61])

In [3]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
np.arange(1,11,1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [7]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.ones([4,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
p=np.ones([3,4])
p

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
p.dtype

dtype('float64')

In [14]:
p.astype(int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
p

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
p8=p.astype('uint8')             #unsigned integer of 8 bit
p8

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint8)

In [17]:
np.random.randint(1,100,5)

array([15, 17, 64, 59, 47])

In [18]:
np.random.randint(1,100,[3,5])

array([[35, 56, 79,  9, 86],
       [10, 93, 36, 72,  3],
       [27, 87, 62, 66, 87]])

In [19]:
np.random.seed(5000)
np.random.randint(1,100,[3,5])

array([[28, 67, 98,  2, 30],
       [ 3, 15,  4, 97, 60],
       [27, 68, 47,  4, 65]])

In [20]:
np.random.rand(3,4)*100

array([[82.19188929, 32.24671905, 90.98561329, 92.65393055],
       [30.78515475,  3.66003632, 18.40615649, 62.0690298 ],
       [65.83740819, 31.15034218, 86.68766811, 13.2184136 ]])

In [21]:
r=np.random.randn(3,4)
r

array([[ 0.21383409, -1.0923307 , -0.2485543 ,  0.26831376],
       [-0.40444905, -0.25812419, -0.20172561, -0.67233178],
       [-1.54609363, -1.07683216,  0.86766531, -0.34190492]])

In [22]:
import random

In [23]:
random.choice(r)

array([-1.54609363, -1.07683216,  0.86766531, -0.34190492])

In [24]:
np.loadtxt('data.txt',dtype='str')

array([['this', 'is', 'a', 'new', 'file'],
       ['here', 'we', 'get', 'some', 'data']], dtype='<U4')

In [25]:
np.loadtxt('data1.txt',delimiter=',')

array([[45., 65., 78., 98.],
       [23., 19.,  3., 98.],
       [ 1.,  4.,  5.,  6.]])

In [26]:
a=np.random.randint(10,100,[3,6])
a

array([[53, 96, 11, 32, 39, 76],
       [92, 17, 15, 39, 45, 52],
       [33, 28, 72, 39, 45, 85]])

In [27]:
np.savetxt('data3.txt',a,delimiter='|',fmt='%d')

In [28]:
sum(sum(a))

869

In [29]:
a.sum()

869

In [30]:
a.sum(axis=1)    #row-wise sum

array([307, 260, 302])

In [31]:
a.sum(axis=0)     #column-wise sum

array([178, 141,  98, 110, 129, 213])

In [32]:
a.mean(axis=1)

array([51.16666667, 43.33333333, 50.33333333])

In [33]:
a.max(axis=1)

array([96, 92, 85])

In [34]:
a

array([[53, 96, 11, 32, 39, 76],
       [92, 17, 15, 39, 45, 52],
       [33, 28, 72, 39, 45, 85]])

In [35]:
a.argmax(axis=1)

array([1, 0, 5], dtype=int64)

In [36]:
a.argmax(axis=0)

array([1, 0, 2, 1, 1, 2], dtype=int64)

In [37]:
a.argmax()

1

In [38]:
a.flatten()

array([53, 96, 11, 32, 39, 76, 92, 17, 15, 39, 45, 52, 33, 28, 72, 39, 45,
       85])