In [1]:
#working with python modules

In [2]:
!python -m pip install numpy

In [3]:
import numpy

In [4]:
import keyword

In [5]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [6]:
import keyword as kw
kw.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [7]:
from keyword import kwlist
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [8]:
import numpy as np

In [9]:
a=np.array([])
a

array([], dtype=float64)

In [10]:
b=np.array([3,4,5,6,7])
b

array([3, 4, 5, 6, 7])

In [11]:
len(a),len(b)

(0, 5)

In [12]:
a.dtype

dtype('float64')

In [13]:
b.dtype

dtype('int32')

In [14]:
b.shape

(5,)

In [15]:
b.size

5

In [16]:
a.shape


(0,)

In [17]:
a.size

0

In [18]:
a.ndim

1

In [19]:
b.ndim      #n-dimensional

1

In [20]:
type(a)

numpy.ndarray

In [21]:
c = np.array([[2,3,4], [4,5,6], [7,8,9], [10,11,12]])
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
c.shape

(4, 3)

In [23]:
d = np.array([[[2],[3],[4]], [[4],[5],[6]], [[7],[8],[9]], [[10],[11],[12]]])
d

array([[[ 2],
        [ 3],
        [ 4]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [24]:
d.shape

(4, 3, 1)

In [25]:
c.sum(axis=1)

array([ 9, 15, 24, 33])

In [26]:
c.mean(axis=1)

array([ 3.,  5.,  8., 11.])

In [27]:
c[0][1]

3

In [28]:
c[0:2, -1]

array([4, 6])

In [29]:
c[0:2, -1:]

array([[4],
       [6]])